server:
  port: 8080
spring:
  output.ansi.enabled: ALWAYS
  security:
    oauth2:
      authorization-server:
        client:
          demo-client:
            require-authorization-consent: true
            registration:
              client-id: demo
              client-secret: "{bcrypt}$2a$10$lHEIhOIZBybWCzRZOVuko.rFe9oGBtGHnRAU97wgvJZmWQWvkBIm6"
              authorization-grant-types: client_credentials,authorization_code,refresh_token
#              authorized-grant-types: authorization_code
              redirect-uris: http://localhost:8082/login/oauth2/code/reg-client
              scopes: user.read,user.write,openid
              client-authentication-methods: client_secret_basic
            issuer-uri: 127.0.0.1